<x-dashboard
    :qtdProcessosAbertos="$qtdProcessosAbertos"
    :qtdProcessosRetornados="$qtdProcessosRetornados"
    :qtdProcessosEmAndamento="$qtdProcessosEmAndamento"
    :qtdProcessosPendentes="$qtdProcessosPendentes"
    :qtdAtpvsAbertos="$qtdAtpvsAbertos"
    :qtdAtpvsRetornados="$qtdAtpvsRetornados"
    :qtdAtpvsEmAndamento="$qtdAtpvsEmAndamento"
    :qtdAtpvsPendentes="$qtdAtpvsPendentes"
    :qtdAtpvsSolicitadoCancelamento="$qtdAtpvsSolicitadoCancelamento"
    :routeProcessosAbertos="route('despachante.processos', ['status' => 'ab'])"
    :routeProcessosRetornados="route('despachante.processos', ['status' => 'ab', 'retorno' => 1])"
    :routeProcessosEmAndamento="route('despachante.processos', ['status' => 'ea'])"
    :routeProcessosPendentes="route('despachante.processos', ['status' => 'pe'])"
    :routeAtpvsAbertos="route('despachante.atpvs', ['status' => 'ab'])"
    :routeAtpvsRetornados="route('despachante.atpvs', ['status' => 'ab', 'retorno' => 1])"
    :routeAtpvsEmAndamento="route('despachante.atpvs', ['status' => 'ea'])"
    :routeAtpvsPendentes="route('despachante.atpvs', ['status' => 'pe'])"
    :routeAtpvsSolicitadoCancelamento="route('despachante.atpvs', ['status' => 'sc'])"
/>
