name: Laravel CI/CD Pipeline

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          port: ${{secrets.PORT}}
          key: ${{secrets.SSHKEY}}
          script: |
          git pull origin main
          docker build -t laravel_app .
          docker stack deploy -c docker-compose.yml partner-app
          docker service update --force --image laravel_app:latest partner-app_laravel-app
      

