name: Laravel CI/CD Pipeline

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: "production"
            branch: "main"
            migrate_command: "migrate --force"
          - environment: "staging"
            branch: "staging"
            migrate_command: "migrate:refresh --seed"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      if: github.ref == 'refs/heads/${{ matrix.branch }}'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.REMOTE_HOST }}
        username: 'kevin'
        key: ${{ secrets.SECRET_SSH_KEY }}
        port: ${{ vars.REMOTE_PORT }} # Se você usa um porto diferente do padrão (22)
        script: |
          cd /home/kevin/repositories/laravel-app/
          git pull origin ${{ matrix.branch }}
          composer install --no-interaction --prefer-dist --optimize-autoloader
          php artisan ${{ matrix.migrate_command }}
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          # Remova esta linha se não estiver usando Docker com Laravel Sail no servidor
          npm run build
          # any other commands you need to run for the specific environment
