name: Laravel CI/CD Pipeline

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: "production"
            branch: "main"
            migrate_command: "php artisan migrate --force"
          - environment: "staging"
            branch: "staging"
            migrate_command: "php artisan migrate:refresh --seed"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      if: github.ref == 'refs/heads/${{ matrix.branch }}'
      run: |
        ssh -o "StrictHostKeyChecking=no" your-username@${{ secrets['SERVER_IP_'+matrix.environment] }} << 'ENDSSH'
          cd /path/to/your/laravel/project
          git pull origin ${{ matrix.branch }}
          composer install --no-interaction --prefer-dist --optimize-autoloader
          ${{ matrix.migrate_command }}
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          # any other commands you need to run for the specific environment
        ENDSSH
