name: Laravel CI/CD Pipeline

on:
  pull_request_review:
    branches:
      - main
    types:
      - submitted
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          port: ${{secrets.PORT}}
          key: ${{secrets.SSHKEY}}
          script: "eval `ssh-agent` && ssh-add ~/.ssh/github_deploy && cd ~/repositories/despachante-laravel/ && git checkout main && git pull"
      - name: Deploy Docker Stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          port: ${{secrets.PORT}}
          key: ${{secrets.SSHKEY}}
          script: "docker build -t laravel-octane . && docker stack deploy -c ~/repositories/despachante-laravel/docker-compose.yml laravel-app"


